[project]
name = "week03-homework-2"
version = "0.1.0"
description = "week03 homework part2"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.117.1",
    "llama-index>=0.14.2",
    "llama-index-embeddings-dashscope>=0.4.1",
    "llama-index-embeddings-huggingface>=0.6.1",
    "llama-index-llms-openai-like>=0.5.1",
    "llama-index-vector-stores-milvus>=0.9.2",
    "neo4j-graphrag>=1.10.0",
    "pymilvus>=2.6.2",
    "python-multipart>=0.0.20",
    "uvicorn[standard]>=0.37.0",
]

[dependency-groups]
dev = []

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
default = true
