[project]
name = "week11-homework"
version = "0.1.0"
description = "基于智能体协作的狼人杀游戏系统"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"python-dotenv",
	"langchain",
	"langgraph",
	"pymilvus",
	"langchain-openai",
	"streamlit",
	"langchain-community",
	"langchain-huggingface>=1.1.0",
	"sentence-transformers>=5.1.2",
]
